/*
  QLC+ Effect Script: Wander
  Pan/tilt fixtures drift organically using overlapping sine waves at
  incommensurable frequencies — each fixture wanders on its own path.
  No joystick needed; fully time-driven.
*/
(function() {
    var effect = new Object;
    effect.apiVersion  = 1;
    effect.name        = "Wander";
    effect.description = "Organic pan/tilt drift — each fixture has its own wandering path";
    effect.author      = "QLC+";
    effect.fixtureTypes = ["moving"];
    effect.notes        = "Each fixture drifts in a uniquely wandering pan/tilt path generated by a sum of low-frequency sines. Diverge spreads the individual paths apart so fixtures don't shadow each other. Radius controls maximum excursion from centre; speed sets how fast the paths evolve. Great for atmospheric ambient movement.";

    effect.inputs = [];

    // Position-only effect: no colour/dimmer. Add a Colour/Dimmer look to the
    // scene for those; this effect drives pan/tilt and composes with them.

    effect.parameters = [
        { name: "speed",    description: "Wander speed (1=slow drift, 5=agitated)", min: 0.1,  max: 5.0,   defaultValue: 1.0  },
        { name: "radius",   description: "Range fraction of pan/tilt total (0-1)",  min: 0.01, max: 1.0,   defaultValue: 0.3  },
        { name: "center",   description: "Pan centre (0=left, 0.5=mid, 1=right)",   min: 0.0,  max: 1.0,   defaultValue: 0.5  },
        { name: "tcenter",  description: "Tilt centre (0=up, 0.5=mid, 1=down)",     min: 0.0,  max: 1.0,   defaultValue: 0.5  },
        { name: "diverge",  description: "Phase spread so fixtures don't clump",    min: 0.0,  max: 1.0,   defaultValue: 1.0  }
    ];

    // Sum of three incommensurable sines → smooth pseudo-random drift −1..+1
    function drift(t, seed, speed) {
        return 0.45 * Math.sin(t * speed * 0.31 + seed * 5.3)
             + 0.35 * Math.sin(t * speed * 0.71 + seed * 2.7)
             + 0.20 * Math.sin(t * speed * 1.37 + seed * 8.1);
    }

    effect.tick = function(fixtures, inputs, palettes, params, state) {
        var t       = inputs._time !== undefined ? inputs._time : 0;
        var speed   = params.speed   !== undefined ? params.speed   : 1.0;
        var radius  = params.radius  !== undefined ? params.radius  : 0.3;
        var center  = params.center  !== undefined ? params.center  : 0.5;
        var tcenter = params.tcenter !== undefined ? params.tcenter : 0.5;
        var diverge = params.diverge !== undefined ? params.diverge : 1.0;

        return fixtures.map(function(f, i) {
            if (!f.hasPanTilt) return {};

            var seed = i * diverge * 3.14159;
            var pan  = (center + radius * drift(t, seed,           speed)) * f.panRange;
            var tilt = (tcenter + radius * drift(t, seed + 100.0,  speed)) * f.tiltRange;

            var intent = {
                pan:  Math.max(0, Math.min(f.panRange,  pan)),
                tilt: Math.max(0, Math.min(f.tiltRange, tilt))
            };

            // Position effect: only touch dimmer/colour when a palette is
            // bound. Otherwise omit those keys so the scene's own Dimmer/Color
            // looks fall through (Override only wins channels we emit).
            if (palettes.dimmer && palettes.dimmer.dimmer !== undefined)
                intent.dimmer = palettes.dimmer.dimmer;

            if (palettes.color && palettes.color.r !== undefined) {
                intent.r = palettes.color.r;
                intent.g = palettes.color.g;
                intent.b = palettes.color.b;
            }

            return intent;
        });
    };

    return effect;
})()
